export const l10n = {
  login: { id: "Masuk", en: "Login" },
  register: { id: "Daftar", en: "Register" },
  forgot_password: { id: "Lupa Password", en: "Forgotten Password" },
  library: { id: "Perpustakaan", en: "Library" },
  wishlist_library: { id: "Wishlist Perpustakaan", en: "Library Wishlist" },
  colportage: { id: "Kolportase", en: "Colportage" },
  room_rental: { id: "Peminjaman Ruangan", en: "Room Rental" },
  phone_number: { id: "Nomor Handphone", en: "Handphone Number" },
  password_not_match: { id: "Konfirmasi Kata Sandi tidak Sama Dengan Password Baru", en: "Confirmation Password Not Match with new Password"},
  password: { id: "Kata Sandi", en: "Password"},
  password_current: { id: "Kata Sandi Sekarang", en: "Current Password"},
  password_new: { id: "Kata Sandi Baru", en: "New Password"},
  password_confirmation: { id: "Konfirmasi Kata Sandi", en: "Confirm Password"},
  password_current_failed: { id: "Kata Sandi Sekarang Anda Salah", en: "Your Current Password is Wrong"},
  password_current_required: { id: "Kata Sandi Sekarang Anda Wajib Diisi", en: "Required Input Your Current Password"},
  password_new_required: { id: "Kata Sandi Baru Anda Wajib Diisi", en: "Required Input Your New Password"},
  password_confirmation_required: { id: "Konfirmasi Kata Sandi Anda Wajib Diisi", en: "Required Input Your Confirm Password"},
  input_phone_number_required: {
    id: "Nomor Handphone Anda Wajib Diisi",
    en: "Required Input Your Handphone Number",
  },
  input_password_required: {
    id: "Kata Sandi Anda Wajib Diisi",
    en: "Required Input Your Password",
  },
  input_phone_number: {
    id: "Masukkan Nomor Handphone Anda",
    en: "Input Your Handphone Number",
  },
  input_password: {
    id: "Masukkan Kata Sandi Anda",
    en: "Input Your Password",
  },
  next: { id: "Lanjut", en: "Next" },
  send: { id: "Kirim", en: "Send" },
  not_have_account: {
    id: "Belum punya akun ?",
    en: "Don't have an account yet ?",
  },
  full_name: { id: "Nama Lengkap", en: "Full Name" },
  email: { id: "Email", en: "Email" },
  have_account: { id: "Sudah punya akun ?", en: "Already have an account ?" },
  kode_otp: { id: "Kode OTP", en: "Code OTP" },
  input_otp: { id: " (Masukan Kode OTP Anda)", en: " (Enter Your OTP Code)" },
  inbox: { id: "Kotak Masuk", en: "Inbox" },
  all_must_required: { id: "Semua harus diisi", en: "All must required" },
  something_wrong: { id: "terjadi masalah", en: "something wrong" },
  select_location: { id: "Pilih Lokasi", en: "Select Location" },
  select_book: { id: "Pilih Buku", en: "Select Book" },
  greatingHome: { id: "Halo", en: "Hello" },
  history: { id: "Riwayat", en: "History" },
  cart: { id: "Keranjang", en: "Cart" },
  rent: { id: "Pinjam", en: "Rent" },
  add_cart: { id: "+ Keranjang", en: "+ Cart" },
  available: { id: "Tersedia", en: "Available" },
  not_available: { id: "Tidak Tersedia", en: "Not Available" },
  description: { id: "Deskripsi", en: "Description" },
  loan_time: { id: "Waktu Peminjaman", en: "Borrowing Time" },
  success_add_cart: {
    id: "Berhasil menambahkan keranjang",
    en: "Success add to cart",
  },
  failed_add_cart: {
    id: "Gagal menambahkan keranjang",
    en: "Failed add to cart",
  },
  failed_rent: { id: "Gagal menyewa buku", en: "Failed rent book" },
  done: { id: "Selesai", en: "Done" },
  rental: { id: "Peminjaman", en: "Borrowing" },
  text_tanda_trima: {
    id: "Silakan ambil buku dan tunjukkan kepada admin untuk peminjaman buku",
    en: "Please take the book and show it to the admin for book borrowing",
  },
  purchase: { id: "Pembelian", en: "Purchase" },
  number_of_books: { id: "Jumlah Buku", en: "Number Of Books" },
  loan_date: { id: "Tanggal Peminjaman", en: "Borrowing Date" },
  Return_Date: { id: "Tanggal Pengembalian", en: "Return Date" },
  Profile: { id: "Akun", en: "Profile" },
  regis_membership: { id: "Daftar Membership", en: "Register Membership" },
  renew_membership: { id: "Perpanjang Membership", en: "Renew Membership" },
  benefits_membership: {
    id: "Keuntungan Menjadi Membership",
    en: "Benefits of being a Membership",
  },
  please_fill_form_membership: {
    id: "Silahkan isi form di bawah ini untuk daftar bergabung menjadi membership.",
    en: "Please fill in the form below to register to join as a membership.",
  },
  fee_membership: {
    id: "Biaya Daftar Membership",
    en: "Membership Registration Fee",
  },
  year: { id: "Tahun", en: "Year" },
  no_anggota: { id: "Nomor Anggota Jemaat", en: "Church Member Number" },
  nama_anggota: { id: "Nama Anggota Jemaat", en: "Church Member Name" },
  tanggal_lahir: { id: "Tanggal Lahir", en: "Date of birth" },
  alamat: { id: "Alamat", en: "Address" },
  kode_pos: { id: "Kode Pos", en: "Postal Code" },
  kelas: { id: "Kelas", en: "Class" },
  kebaktian: { id: "Kebaktian", en: "Church Service" },
  metode_pembayaran: { id: "Metode Pembayaran", en: "Payment Method" },
  pembayaran: { id: "Pembayaran", en: "Payment" },
  silahkan_melakukan_pembayaran: {
    id: "Silahkan melakukan pembayaran sebelum :",
    en: "Please make payment before:",
  },
  nomor_va: { id: "Nomor Virtual Account", en: "Virtual Account Number" },
  lihat_status_pembayaran: {
    id: "Lihat Status Pembayaran",
    en: "View Payment Status",
  },
  success: { id: "Sukses", en: "Success" },
  message_tanda_terima_pendaftaran: {
    id: "Telah diterima iuran pendaftaran / perpanjanfan Anggota Perpustakaan GKY Pluit",
    en: "GKY Pluit Library Membership Registration Fees has been accepted",
  },
  change_language: { id: "Ganti Bahasa", en: "Change Language" },
  change_password: { id: "Ganti Password", en: "Change Password" },
  save: { id: "Simpan", en: "Save" },
  edit_profile: { id: "Edit Akun", en: "Edit Profile" },
  delete_account: { id: "Hapus Akun", en: "Delete Account" },
  delete: { id: "Hapus", en: "Delete" },
  success_delete_book: {
    id: "Sukses Menghapus Buku",
    en: "Success delete book",
  },
  failed_delete_book: { id: "Gagal Menghapus Buku", en: "Failed delete book" },
  jadwal_pengembalian: { id: "Jadwal Pengembalian", en: "Return Schedule" },
  buku: { id: "Buku", en: "Book" },
  durasi_peminjaman: { id: "Durasi Peminjaman", en: "Borrowing Duration" },
  days: { id: "Hari", en: "Days" },
  tanggal_pengambilan: { id: "Tanggal Pengambilan", en: "Pick-up Time" },
  detail_history: { id: "Detail Histori", en: "History Detail" },
  please_login: {
    id: "Silahkan Melakukan Masuk/Daftar Terlebih Dahulu",
    en: "Please Login / Register First",
  },
  success_email: { id: "Email Success", en: "Success Email" },
};
