export const l10n = {
  login: { id: "Masuk", en: "Login" },
  register: { id: "Daftar", en: "Register" },
  forgot_password: { id: "Lupa Password", en: "Forgotten Password" },
  faq: { id: "FAQ", en: "FAQ" },
  welcome_faq: { id: "Selamat datang di halaman FAQ Apple App Store untuk aplikasi Perpustakaan Gereja Kristus Yesus Jemaat Pluit kami! Berikut adalah beberapa pertanyaan dan jawaban yang umum diajukan:", en: "Welcome to the Apple App Store FAQ page for our Church Library app! Here are some commonly asked questions and answers:" },
  q1: { id: "T: Apa itu aplikasi Perpustakaan Gereja?", en: "Q: What is the Church Library app? " },
  a1: { id: "J: Aplikasi Perpustakaan Gereja Kristus Yesus Jemaat Pluit adalah aplikasi seluler yang dirancang untuk anggota komunitas gereja kita. Ini memungkinkan pengguna untuk menelusuri dan mencari koleksi buku-buku , DVD, CD, dan materi lainnya yang tersedia di perpustakaan gereja atas Item yang diperlukan langsung dari perangkat seluler mereka dan memesan item tersebut .", en: "A: The Church Library app is a mobile app designed for the members of our church community. It allows users to browse and search our church library's collection of books, DVDs, CDs, and other materials, reserve items, and check out items directly from their mobile device." },
  q2: { id: "T: Apakah aplikasi Perpustakaan Gereja tersedia di Apple App Store?", en: "Q: Is the Church Library app available on the Apple App Store? " },
  a2: { id: "J: Ya, aplikasi Perpustakaan Gereja tersedia di Apple App Store secara gratis.", en: "A: Yes, the Church Library app is available on the Apple App Store for free." },
  q3: { id: "T: Adakah yang dapat mengunduh dan menggunakan aplikasi Perpustakaan Gereja?", en: "Q: Can anyone download and use the Church Library app? " },
  a3: { id: "J: Aplikasi Perpustakaan Gereja dirancang untuk anggota komunitas / jemaat gereja kita. Untuk menggunakan aplikasi ini, Anda harus memiliki akun member dengan perpustakaan gereja kami. Jika Anda adalah anggota komunitas / jemaat gereja kami dan belum memiliki akun, silakan hubungi administrasi perpustakaan gereja kami untuk mendaftar menjadi anggota perpustakaan .", en: "A: The Church Library app is designed for members of our church community. In order to use the app, you need to have an account with our church library. If you're a member of our church community and don't have an account yet, please contact our church library to sign up." },
  q4: { id: "T: Bagaimana cara mengunduh dan menginstal aplikasi Perpustakaan Gereja?", en: "Q: How do I download and install the Church Library app?" },
  a4: { id: "J: Untuk mengunduh dan menginstal aplikasi Perpustakaan Gereja, buka Apple App Store di perangkat iOS Anda dan cari \"Perpustakaan Gereja Kristus Yesus Jemaat Pluit .\" Setelah Anda menemukan aplikasinya, klik tombol \"Dapatkan\" dan ikuti petunjuk di layar untuk menginstal aplikasi.", en: "A: To download and install the Church Library app, go to the Apple App Store on your iOS device and search for \"Church Library.\" Once you've found the app, click the \"Get\" button and follow the on-screen instructions to install the app." },
  q5: { id: "T: Bagaimana cara masuk ke aplikasi Perpustakaan Gereja?", en: "Q: How do I log in to the Church Library app?" },
  a5: { id: "J: Setelah Anda mengunduh dan menginstal aplikasi Perpustakaan Gereja Kristus Yesus Jemaat Pluit , buka aplikasi dan masukkan kredensial akun perpustakaan gereja Anda untuk masuk. Jika Anda belum memiliki akun, silakan hubungi administrasi perpustakaan gereja kami untuk mendaftar.", en: "A: Once you've downloaded and installed the Church Library app, open the app and enter your church library account credentials to log in. If you don't have an account yet, please contact our church library to sign up." },
  q6: { id: "T: Dapatkah saya menelusuri aplikasi Perpustakaan Gereja tanpa masuk? ", en: "Q: Can I browse the Church Library app without logging in? " },
  a6: { id: "J: Anda dapat menelusuri koleksi aplikasi tanpa masuk / login, tetapi Anda tidak akan dapat memesan atau memeriksa item tanpa login ke akun.", en: "A: You can browse the app's collection without logging in, but you won't be able to reserve or check out items without an account." },
  q7: { id: "T: Bagaimana cara mencari item di aplikasi Perpustakaan Gereja? ", en: "Q: How do I search for items in the Church Library app?" },
  a7: { id: "J: Untuk mencari item di aplikasi, gunakan bilah pencarian di bagian atas layar. Anda dapat mencari berdasarkan judul, penulis, atau kata kunci.", en: "A: To search for items in the app, use the search bar at the top of the screen. You can search by title, author, or keyword." },
  q8: { id: "T: Bagaimana cara memesan item di aplikasi Perpustakaan Gereja? ", en: "Q: How do I reserve items in the Church Library app?" },
  a8: { id: "J: Untuk memesan item di aplikasi, temukan item yang ingin Anda pesan dan klik tombol \"Pesan\". Anda akan menerima pemberitahuan saat item tersedia untuk diambil.", en: "A: To reserve items in the app, find the item you want to reserve and click the \"Reserve\" button. You'll receive a notification when the item is available for pickup." },
  q9: { id: "T: Bagaimana cara memeriksa item di aplikasi Perpustakaan Gereja?", en: "Q: How do I check out items in the Church Library app?" },
  a9: { id: "J: Untuk memeriksa item di aplikasi, temukan item yang ingin Anda periksa dan klik tombol \"Check Out\". Anda akan menerima pemberitahuan saat item jatuh tempo.", en: "A: To check out items in the app, find the item you want to check out and click the \"Check Out\" button. You'll receive a notification when the item is due." },
  q10: { id: "T: Dapatkah saya memperbarui item di aplikasi Perpustakaan Gereja?", en: "Q: Can I renew items in the Church Library app? " },
  a10: { id: "J: Anda dapat memperpanjang item di aplikasi jika item tersebut belum dipesan oleh pengguna lain. Untuk memperbarui item, buka halaman akun Anda dan temukan item yang ingin Anda perpanjang. Klik tombol \"Perbarui\" dan ikuti petunjuk di layar.", en: "A: You can renew items in the app if they haven't been reserved by another user. To renew an item, go to your account page and find the item you want to renew. Click the \"Renew\" button and follow the on-screen instructions." },
  q11: { id: "T: Bagaimana cara mengembalikan barang di aplikasi Perpustakaan Gereja?", en: "Q: How do I return items in the Church Library app?" },
  a11: { id: "J:Untuk mengembalikan item yang dipinjam diaplikasi, bawa item fisik ke perpustakaan gereja kami dan akan diperiksa oleh administrasi perpustakaan kami.", en: "A: To return items in the app, bring them to our church library's physical location and check them in with our library staff." },
  q12: { id: "T: Bagaimana cara menghubungi dukungan untuk aplikasi Perpustakaan Gereja?", en: "Q: How do I contact support for the Church Library app" },
  a12: { id: "J: Jika Anda memiliki pertanyaan atau masalah dengan aplikasi Perpustakaan Gereja, silakan hubungi perpustakaan gereja kami untuk mendapatkan dukungan.", en: "A: If you have any questions or issues with the Church Library app, please contact our church library for support" },
  library: { id: "Perpustakaan", en: "Library" },
  wishlist_library: { id: "Wishlist Perpustakaan", en: "Library Wishlist" },
  colportage: { id: "Kolportase", en: "Colportage" },
  room_rental: { id: "Peminjaman Ruangan", en: "Room Rental" },
  phone_number: { id: "Nomor Handphone", en: "Handphone Number" },
  password_not_match: { id: "Konfirmasi Kata Sandi tidak Sama Dengan Password Baru", en: "Confirmation Password Not Match with new Password"},
  password: { id: "Kata Sandi", en: "Password"},
  password_current: { id: "Kata Sandi Sekarang", en: "Current Password"},
  password_new: { id: "Kata Sandi Baru", en: "New Password"},
  password_confirmation: { id: "Konfirmasi Kata Sandi", en: "Confirm Password"},
  password_current_failed: { id: "Kata Sandi Sekarang Anda Salah", en: "Your Current Password is Wrong"},
  password_current_required: { id: "Kata Sandi Sekarang Anda Wajib Diisi", en: "Required Input Your Current Password"},
  password_new_required: { id: "Kata Sandi Baru Anda Wajib Diisi", en: "Required Input Your New Password"},
  password_confirmation_required: { id: "Konfirmasi Kata Sandi Anda Wajib Diisi", en: "Required Input Your Confirm Password"},
  input_phone_number_required: {
    id: "Nomor Handphone Anda Wajib Diisi",
    en: "Required Input Your Handphone Number",
  },
  input_password_required: {
    id: "Kata Sandi Anda Wajib Diisi",
    en: "Required Input Your Password",
  },
  input_phone_number: {
    id: "Masukkan Nomor Handphone Anda",
    en: "Input Your Handphone Number",
  },
  input_password: {
    id: "Masukkan Kata Sandi Anda",
    en: "Input Your Password",
  },
  next: { id: "Lanjut", en: "Next" },
  send: { id: "Kirim", en: "Send" },
  not_have_account: {
    id: "Belum punya akun ?",
    en: "Don't have an account yet ?",
  },
  full_name: { id: "Nama Lengkap", en: "Full Name" },
  email: { id: "Email", en: "Email" },
  have_account: { id: "Sudah punya akun ?", en: "Already have an account ?" },
  kode_otp: { id: "Kode OTP", en: "Code OTP" },
  input_otp: { id: " (Masukan Kode OTP Anda)", en: " (Enter Your OTP Code)" },
  inbox: { id: "Kotak Masuk", en: "Inbox" },
  all_must_required: { id: "Semua harus diisi", en: "All must required" },
  something_wrong: { id: "terjadi masalah", en: "something wrong" },
  select_location: { id: "Pilih Lokasi", en: "Select Location" },
  select_book: { id: "Pilih Buku", en: "Select Book" },
  greatingHome: { id: "Halo", en: "Hello" },
  history: { id: "Riwayat", en: "History" },
  cart: { id: "Keranjang", en: "Cart" },
  rent: { id: "Pinjam", en: "Rent" },
  add_cart: { id: "+ Keranjang", en: "+ Cart" },
  available: { id: "Tersedia", en: "Available" },
  not_available: { id: "Tidak Tersedia", en: "Not Available" },
  description: { id: "Deskripsi", en: "Description" },
  loan_time: { id: "Waktu Peminjaman", en: "Borrowing Time" },
  success_add_cart: {
    id: "Berhasil menambahkan keranjang",
    en: "Success add to cart",
  },
  failed_add_cart: {
    id: "Gagal menambahkan keranjang",
    en: "Failed add to cart",
  },
  failed_rent: { id: "Gagal menyewa buku", en: "Failed rent book" },
  done: { id: "Selesai", en: "Done" },
  rental: { id: "Peminjaman", en: "Borrowing" },
  text_tanda_trima: {
    id: "Silakan ambil buku dan tunjukkan kepada admin untuk peminjaman buku",
    en: "Please take the book and show it to the admin for book borrowing",
  },
  purchase: { id: "Pembelian", en: "Purchase" },
  number_of_books: { id: "Jumlah Buku", en: "Number Of Books" },
  loan_date: { id: "Tanggal Peminjaman", en: "Borrowing Date" },
  Return_Date: { id: "Tanggal Pengembalian", en: "Return Date" },
  Profile: { id: "Akun", en: "Profile" },
  regis_membership: { id: "Daftar Membership", en: "Register Membership" },
  renew_membership: { id: "Perpanjang Membership", en: "Renew Membership" },
  benefits_membership: {
    id: "Keuntungan Menjadi Membership",
    en: "Benefits of being a Membership",
  },
  please_fill_form_membership: {
    id: "Silahkan isi form di bawah ini untuk daftar bergabung menjadi membership.",
    en: "Please fill in the form below to register to join as a membership.",
  },
  fee_membership: {
    id: "Biaya Daftar Membership",
    en: "Membership Registration Fee",
  },
  year: { id: "Tahun", en: "Year" },
  no_anggota: { id: "Nomor Anggota Jemaat", en: "Church Member Number" },
  nama_anggota: { id: "Nama Anggota Jemaat", en: "Church Member Name" },
  tanggal_lahir: { id: "Tanggal Lahir", en: "Date of birth" },
  alamat: { id: "Alamat", en: "Address" },
  kode_pos: { id: "Kode Pos", en: "Postal Code" },
  kelas: { id: "Kelas", en: "Class" },
  kebaktian: { id: "Kebaktian", en: "Church Service" },
  metode_pembayaran: { id: "Metode Pembayaran", en: "Payment Method" },
  pembayaran: { id: "Pembayaran", en: "Payment" },
  silahkan_melakukan_pembayaran: {
    id: "Silahkan melakukan pembayaran sebelum :",
    en: "Please make payment before:",
  },
  nomor_va: { id: "Nomor Virtual Account", en: "Virtual Account Number" },
  lihat_status_pembayaran: {
    id: "Lihat Status Pembayaran",
    en: "View Payment Status",
  },
  success: { id: "Sukses", en: "Success" },
  message_tanda_terima_pendaftaran: {
    id: "Telah diterima iuran pendaftaran / perpanjanfan Anggota Perpustakaan GKY Pluit",
    en: "GKY Pluit Library Membership Registration Fees has been accepted",
  },
  change_language: { id: "Ganti Bahasa", en: "Change Language" },
  change_password: { id: "Ganti Password", en: "Change Password" },
  save: { id: "Simpan", en: "Save" },
  edit_profile: { id: "Edit Akun", en: "Edit Profile" },
  delete_account: { id: "Hapus Akun", en: "Delete Account" },
  delete: { id: "Hapus", en: "Delete" },
  success_delete_book: {
    id: "Sukses Menghapus Buku",
    en: "Success delete book",
  },
  failed_delete_book: { id: "Gagal Menghapus Buku", en: "Failed delete book" },
  jadwal_pengembalian: { id: "Jadwal Pengembalian", en: "Return Schedule" },
  buku: { id: "Buku", en: "Book" },
  durasi_peminjaman: { id: "Durasi Peminjaman", en: "Borrowing Duration" },
  days: { id: "Hari", en: "Days" },
  tanggal_pengambilan: { id: "Tanggal Pengambilan", en: "Pick-up Time" },
  detail_history: { id: "Detail Histori", en: "History Detail" },
  please_login: {
    id: "Silahkan Melakukan Masuk/Daftar Terlebih Dahulu",
    en: "Please Login / Register First",
  },
  success_email: { id: "Email Success", en: "Success Email" },
  failed_email: { id: "Email Gagal", en: "Failed Email" },
};
